version: '3'
services:
  opensearch:
    build: .
    environment:
      - discovery.type=single-node
      # - bootstrap.memory_lock=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.name=opensearch-cluster-local
      - node.name=opensearch-sentiment-analyzer-1
      - DISABLE_SECURITY_PLUGIN=true
      - logger.org.opensearch.plugins.sentiment-analysis=debug
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - 5601:5601

volumes:
  opensearch-data:
