version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-local-1
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m -Djava.security.policy=/usr/share/opensearch/config/opensearch-security.policy
      - cluster.name=opensearch-cluster-local
      - node.name=opensearch-local-1
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - ./opensearch-security.policy:/usr/share/opensearch/config/opensearch-security.policy:ro
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards-local-1
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - 5601:5601
    depends_on:
      - opensearch
    networks:
      - opensearch-net

  sentiment-analysis-service:
    container_name: sentiment-analysis-service-1
    build: 
      context: ./sentiment-analysis-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=sentiment_analysis_service.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: always
    networks:
      - opensearch-net
    # depends_on:
    #   - opensearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./sentiment-analysis-service:/app

networks:
  opensearch-net:
    driver: bridge

volumes:
  opensearch-data: